<a href="https://colab.research.google.com/github/ArtsemiRyabu/NN_ITP31_2/blob/lab1/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random
from sklearn.metrics import accuracy_score

In [ ]:
def bit_func(x, y):
  return x | y & ~y

In [ ]:
def step_func(x):
  if(x > 0):
    return 1
  else:
    return 0

class Neuron:
  def __init__(self, weights):
    self.weights = weights

  def get_sum(self, x):
    sum = 0
    for i in range(len(self.weights)):
      sum += self.weights[i] * x[i]
    return sum

  def feed(self, x):
    y = step_func(self.get_sum(x))
    return y
    
  def print_params(self):
    n_str = ''
    for i in range(len(self.weights)):
      n_str += str(self.weights[i]) + " "

class Network:
  def __init__(self):
    self.n1 = Neuron([random.randint(-5, 5), random.randint(-5, 5)])
    self.n2 = Neuron([random.randint(-5, 5), random.randint(-5, 5)])
    self.o1 = Neuron([random.randint(-5, 5), random.randint(-5, 5)])
    self.o2 = Neuron([random.randint(-5, 5), random.randint(-5, 5)])
    self.f1 = Neuron([random.randint(-5, 5), random.randint(-5, 5)])

  def printNeurons(self):
    print("[" + str(round(self.n1.weights[0], 2)) + " " + str(round(self.n1.weights[1], 2)) + " " +
                str(round(self.n2.weights[0], 2)) + " " + str(round(self.n2.weights[1], 2)) + " " +
                str(round(self.o1.weights[0], 2)) + " " + str(round(self.n2.weights[1], 2)) + " " +
                str(round(self.o2.weights[0], 2)) + " " + str(round(self.n2.weights[1], 2)) + " " +
                str(round(self.f1.weights[0], 2)) + " " + str(round(self.f1.weights[1], 2)) + "]")
 
  def predict(self, data):
    y_pred = []
    for x in data:
      h1 = self.n1.feed(x)
      h2 = self.n2.feed(x)
      h = [h1, h2]
      r1 = self.o1.feed(h)
      r2 = self.o2.feed(h)
      g = [r1, r2]
      y_pred.append(self.f1.feed(g))
    return(y_pred)

  def trainHebb(self, data, y_trues):
    epochs = 20
    y_preds = self.predict(data)
    acc = accuracy_score(y_trues, y_preds)
    print("acc before learning: %.3f" % (acc))
    self.printNeurons()    
    for epoch in range(epochs):
      for x, y_true in zip(data, y_trues):
        h1 = self.n1.feed(x)
        h2 = self.n2.feed(x)
        h = [h1, h2]
        r1 = self.o1.feed(h)
        r2 = self.o2.feed(h)
        g = [r1, r2]
        out1 = self.f1.feed(g)
        if(out1 > y_true):
          for i in range(len(x)):
            self.n1.weights[i] -= x[i]
            self.n2.weights[i] -= x[i]
            self.o1.weights[i] -= h[i]
            self.o2.weights[i] -= h[i]
            self.f1.weights[i] -= g[i]
        elif(out1 < y_true):
          for i in range(len(x)):
            self.n1.weights[i] += x[i]
            self.n2.weights[i] += x[i]
            self.o1.weights[i] += h[i]
            self.o2.weights[i] += h[i]
            self.f1.weights[i] += g[i]
      y_preds = self.predict(data)
      acc = accuracy_score(y_trues, y_preds)
      print("Epoch %d acc: %.3f" % (epoch, acc))
      self.printNeurons()
    y_preds = self.predict(data)
    acc = accuracy_score(y_trues, y_preds)
    print("acc: " + str(acc))
    self.printNeurons()
      
all_data = np.array([
  [0, 0],
  [1, 0],
  [0, 1],
  [1, 1],
])

all_y_trues = np.array([
  0,
  1,
  0,
  1,
])

network = Network()
network.trainHebb(all_data, all_y_trues)

acc before learning: 0.500
[-4 -1 4 1 -1 1 0 1 2 -2]
Epoch 0 acc: 0.500
[-2 0 6 2 -1 2 0 2 2 0]
Epoch 1 acc: 0.750
[0 0 8 2 -1 2 0 2 2 1]
Epoch 2 acc: 0.750
[1 0 9 2 -1 2 0 2 2 1]
Epoch 3 acc: 0.750
[2 0 10 2 -1 2 0 2 2 1]
Epoch 4 acc: 0.750
[3 0 11 2 0 2 1 2 2 1]
Epoch 5 acc: 0.750
[4 0 12 2 1 2 2 2 2 1]
Epoch 6 acc: 0.750
[5 0 13 2 2 2 3 2 2 1]
Epoch 7 acc: 1.000
[5 -1 13 1 2 1 3 1 2 0]
Epoch 8 acc: 1.000
[5 -1 13 1 2 1 3 1 2 0]
Epoch 9 acc: 1.000
[5 -1 13 1 2 1 3 1 2 0]
Epoch 10 acc: 1.000
[5 -1 13 1 2 1 3 1 2 0]
Epoch 11 acc: 1.000
[5 -1 13 1 2 1 3 1 2 0]
Epoch 12 acc: 1.000
[5 -1 13 1 2 1 3 1 2 0]
Epoch 13 acc: 1.000
[5 -1 13 1 2 1 3 1 2 0]
Epoch 14 acc: 1.000
[5 -1 13 1 2 1 3 1 2 0]
acc: 1.0
[5 -1 13 1 2 1 3 1 2 0]
